version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-nac-node-policies/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-nac-node-policies/actions/workflows/test.yml)

  # Terraform ACI Node Policies Module

  A Terraform module to configure ACI Node Policies.

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
